### ISSUE TITLE
Search types on "Voices" and "Resources" page

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#39] opened 2016-08-17 12:10 UTC
We would need the option to change search types (such as Videos, Interviews, Reports, Guidance tools etc.) page-specifically. For now, search types are the same on both the "Voices" and "Resources" page. This is not the best solution. For example, searching for "Guidance tools" on the "Voices" page does not make sense. Also, the search results are presented differently on each page, which does not always look good (see attached images). 

Resources search produces a clean result when looking for "Guidance tools":
![resources search](https://cloud.githubusercontent.com/assets/19553399/17735632/9e3e13a4-6483-11e6-9640-f210e1f106da.png)

However, if a person looks for "Guidance tools" through the Voices page: 
![voices search](https://cloud.githubusercontent.com/assets/19553399/17735657/ba4e4564-6483-11e6-8513-46dd35406dbd.png)

**Comment by UncommonUnion** [comment] 2016-08-18 18:18
Ok.We made several changes to give you more control.

Under categories, there are now 2 "types" -
• Resource Type (use for resources)
• Type (use for voices)

The subcategories when searching will reflect however you tweak the categories.

Note that there is a video type for BOTH resources (Resource Type) AND voices (Type). If you want a video to be accessible to both (which I think will probably not be the case) the video subcategory needs to be check for BOTH.

Finally, there is a new category called "voice" ... For content to appear in the Voices section at all, this needs to be checked as well. This assures that content can appear in voices if it is not otherwise categorized (not yet given a type, etc.)

We've reassigned content as an example.

Finally, as for the images and layout; this is by design. The various layouts go back to the wireframes. The voices are meant to be more story-like / human / with an emphasis on media formats (you can play the video, etc.) -- and resources are standard indexical result to serve research. 

Regarding thumbnails, make sure appropriately and consistently sized images are uploaded as thumbnails. The graphical images of the handbook are geometric, so variation is more noticeable, but this shouldn't be as much of an issue now that we've allowed for filtering this content out.

**Closed as completed by UncommonUnion** 2016-08-18 18:18 UTC

**Comment by lamminmaki** [comment] 2016-08-19 07:43
OK!
